"""Added user profile fields

Revision ID: 4c4c620f5607
Revises: 9f59666d5c5d
Create Date: 2026-04-15 21:00:20.568471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4c620f5607'
down_revision = '9f59666d5c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('joined_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('accommodation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('hometown', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interests')
        batch_op.drop_column('hometown')
        batch_op.drop_column('accommodation')
        batch_op.drop_column('joined_date')
        batch_op.drop_column('year_of_study')
        batch_op.drop_column('course')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
