"""Added user profile fields

Revision ID: 906fcd186a16
Revises: 4c4c620f5607
Create Date: 2026-04-15 21:12:13.774157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906fcd186a16'
down_revision = '4c4c620f5607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
